name: Xama

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:

    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install NPM dependencies
      run: |
        npm install

    - name: Run Linting
      run: composer run-script lint

    - name: Run Test Suites
      run: composer run-script test

    - name: Run Test Coverage
      run: |
        composer run-script coverage
        cat cobertura.xml

    - name: Report Coveralls
      run: curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls --repo-token=$COVERALLS_REPO_TOKEN --file=cobertura.xml
